// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dynamicInfoFieldNames          = builder.RawFieldNames(&DynamicInfo{})
	dynamicInfoRows                = strings.Join(dynamicInfoFieldNames, ",")
	dynamicInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(dynamicInfoFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dynamicInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(dynamicInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDynamicInfoIdPrefix     = "cache:dynamicInfo:id:"
	cacheDynamicInfoSiteIdPrefix = "cache:dynamicInfo:siteId:"
)

type (
	dynamicInfoModel interface {
		Insert(ctx context.Context, data *DynamicInfo) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*DynamicInfo, error)
		FindOneBySiteId(ctx context.Context, siteId string) (*DynamicInfo, error)
		Update(ctx context.Context, data *DynamicInfo) error
		Delete(ctx context.Context, id string) error
	}

	defaultDynamicInfoModel struct {
		sqlc.CachedConn
		table string
	}

	DynamicInfo struct {
		Id           string         `db:"id"`            // Unique identifier for the dynamic info record (e.g., UUID)
		SiteId       string         `db:"site_id"`       // Foreign key referencing the sites table, unique as one dynamic info per site
		OpeningHours sql.NullString `db:"opening_hours"` // Structured opening hours (e.g., {"weekday": "9am-5pm", "weekend": "10am-4pm"})
		TicketPrice  string         `db:"ticket_price"`  // Ticket price information (e.g., "Adult: $20, Child: $10")
		Notices      sql.NullString `db:"notices"`       // Array of important notices or announcements (e.g., ["Closed for renovation", "Special event this weekend"])
		UpdatedAt    time.Time      `db:"updated_at"`    // Timestamp of when this information was last updated
	}
)

func newDynamicInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDynamicInfoModel {
	return &defaultDynamicInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`dynamic_info`",
	}
}

func (m *defaultDynamicInfoModel) Delete(ctx context.Context, id string) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	dynamicInfoIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoIdPrefix, id)
	dynamicInfoSiteIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoSiteIdPrefix, data.SiteId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, dynamicInfoIdKey, dynamicInfoSiteIdKey)
	return err
}

func (m *defaultDynamicInfoModel) FindOne(ctx context.Context, id string) (*DynamicInfo, error) {
	dynamicInfoIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoIdPrefix, id)
	var resp DynamicInfo
	err := m.QueryRowCtx(ctx, &resp, dynamicInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dynamicInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDynamicInfoModel) FindOneBySiteId(ctx context.Context, siteId string) (*DynamicInfo, error) {
	dynamicInfoSiteIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoSiteIdPrefix, siteId)
	var resp DynamicInfo
	err := m.QueryRowIndexCtx(ctx, &resp, dynamicInfoSiteIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `site_id` = ? limit 1", dynamicInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, siteId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDynamicInfoModel) Insert(ctx context.Context, data *DynamicInfo) (sql.Result, error) {
	dynamicInfoIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoIdPrefix, data.Id)
	dynamicInfoSiteIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoSiteIdPrefix, data.SiteId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, dynamicInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.SiteId, data.OpeningHours, data.TicketPrice, data.Notices)
	}, dynamicInfoIdKey, dynamicInfoSiteIdKey)
	return ret, err
}

func (m *defaultDynamicInfoModel) Update(ctx context.Context, newData *DynamicInfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	dynamicInfoIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoIdPrefix, data.Id)
	dynamicInfoSiteIdKey := fmt.Sprintf("%s%v", cacheDynamicInfoSiteIdPrefix, data.SiteId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dynamicInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SiteId, newData.OpeningHours, newData.TicketPrice, newData.Notices, newData.Id)
	}, dynamicInfoIdKey, dynamicInfoSiteIdKey)
	return err
}

func (m *defaultDynamicInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDynamicInfoIdPrefix, primary)
}

func (m *defaultDynamicInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dynamicInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDynamicInfoModel) tableName() string {
	return m.table
}
