// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	multimediaFieldNames          = builder.RawFieldNames(&Multimedia{})
	multimediaRows                = strings.Join(multimediaFieldNames, ",")
	multimediaRowsExpectAutoSet   = strings.Join(stringx.Remove(multimediaFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	multimediaRowsWithPlaceHolder = strings.Join(stringx.Remove(multimediaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMultimediaIdPrefix = "cache:multimedia:id:"
)

type (
	multimediaModel interface {
		Insert(ctx context.Context, data *Multimedia) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Multimedia, error)
		Update(ctx context.Context, data *Multimedia) error
		Delete(ctx context.Context, id string) error
	}

	defaultMultimediaModel struct {
		sqlc.CachedConn
		table string
	}

	Multimedia struct {
		Id          string    `db:"id"`          // Unique identifier for the multimedia resource (e.g., UUID)
		SiteId      string    `db:"site_id"`     // Foreign key referencing the sites table
		Type        string    `db:"type"`        // Type of multimedia (e.g., image, video, audio)
		Url         string    `db:"url"`         // URL or path to the multimedia file (managed by media service)
		Description string    `db:"description"` // Description of the multimedia resource
		CreatedAt   time.Time `db:"created_at"`  // Timestamp of when the record was created
		UpdatedAt   time.Time `db:"updated_at"`  // Timestamp of when the record was last updated
	}
)

func newMultimediaModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMultimediaModel {
	return &defaultMultimediaModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`multimedia`",
	}
}

func (m *defaultMultimediaModel) Delete(ctx context.Context, id string) error {
	multimediaIdKey := fmt.Sprintf("%s%v", cacheMultimediaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, multimediaIdKey)
	return err
}

func (m *defaultMultimediaModel) FindOne(ctx context.Context, id string) (*Multimedia, error) {
	multimediaIdKey := fmt.Sprintf("%s%v", cacheMultimediaIdPrefix, id)
	var resp Multimedia
	err := m.QueryRowCtx(ctx, &resp, multimediaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", multimediaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMultimediaModel) Insert(ctx context.Context, data *Multimedia) (sql.Result, error) {
	multimediaIdKey := fmt.Sprintf("%s%v", cacheMultimediaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, multimediaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.SiteId, data.Type, data.Url, data.Description)
	}, multimediaIdKey)
	return ret, err
}

func (m *defaultMultimediaModel) Update(ctx context.Context, data *Multimedia) error {
	multimediaIdKey := fmt.Sprintf("%s%v", cacheMultimediaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, multimediaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SiteId, data.Type, data.Url, data.Description, data.Id)
	}, multimediaIdKey)
	return err
}

func (m *defaultMultimediaModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMultimediaIdPrefix, primary)
}

func (m *defaultMultimediaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", multimediaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMultimediaModel) tableName() string {
	return m.table
}
