// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sitesFieldNames          = builder.RawFieldNames(&Sites{})
	sitesRows                = strings.Join(sitesFieldNames, ",")
	sitesRowsExpectAutoSet   = strings.Join(stringx.Remove(sitesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sitesRowsWithPlaceHolder = strings.Join(stringx.Remove(sitesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSitesIdPrefix = "cache:sites:id:"
)

type (
	sitesModel interface {
		Insert(ctx context.Context, data *Sites) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Sites, error)
		Update(ctx context.Context, data *Sites) error
		Delete(ctx context.Context, id string) error
	}

	defaultSitesModel struct {
		sqlc.CachedConn
		table string
	}

	Sites struct {
		Id               string         `db:"id"`                // Unique identifier for the site (e.g., UUID)
		Name             string         `db:"name"`              // Name of the site
		Description      sql.NullString `db:"description"`       // Detailed description of the site
		Category         string         `db:"category"`          // Category of the site (e.g., Museum, Monument, Landmark)
		Region           string         `db:"region"`            // Geographical area or city where the site is located
		HistoricalPeriod string         `db:"historical_period"` // Historical period the site belongs to (e.g., Ming Dynasty, Roman Empire)
		Latitude         float64        `db:"latitude"`          // Latitude coordinate of the site
		Longitude        float64        `db:"longitude"`         // Longitude coordinate of the site
		Address          string         `db:"address"`           // Full address of the site
		CreatedAt        time.Time      `db:"created_at"`        // Timestamp of when the record was created
		UpdatedAt        time.Time      `db:"updated_at"`        // Timestamp of when the record was last updated
	}
)

func newSitesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSitesModel {
	return &defaultSitesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sites`",
	}
}

func (m *defaultSitesModel) Delete(ctx context.Context, id string) error {
	sitesIdKey := fmt.Sprintf("%s%v", cacheSitesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sitesIdKey)
	return err
}

func (m *defaultSitesModel) FindOne(ctx context.Context, id string) (*Sites, error) {
	sitesIdKey := fmt.Sprintf("%s%v", cacheSitesIdPrefix, id)
	var resp Sites
	err := m.QueryRowCtx(ctx, &resp, sitesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sitesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSitesModel) Insert(ctx context.Context, data *Sites) (sql.Result, error) {
	sitesIdKey := fmt.Sprintf("%s%v", cacheSitesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sitesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Description, data.Category, data.Region, data.HistoricalPeriod, data.Latitude, data.Longitude, data.Address)
	}, sitesIdKey)
	return ret, err
}

func (m *defaultSitesModel) Update(ctx context.Context, data *Sites) error {
	sitesIdKey := fmt.Sprintf("%s%v", cacheSitesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sitesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Description, data.Category, data.Region, data.HistoricalPeriod, data.Latitude, data.Longitude, data.Address, data.Id)
	}, sitesIdKey)
	return err
}

func (m *defaultSitesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSitesIdPrefix, primary)
}

func (m *defaultSitesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sitesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSitesModel) tableName() string {
	return m.table
}
