// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: site.proto

package siteservice

import (
	"context"

	"site/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateSiteReq         = pb.CreateSiteReq
	DeleteSiteReq         = pb.DeleteSiteReq
	DeleteSiteResp        = pb.DeleteSiteResp
	DynamicInfo           = pb.DynamicInfo
	GetSiteByIDReq        = pb.GetSiteByIDReq
	GetSiteDynamicInfoReq = pb.GetSiteDynamicInfoReq
	GetSiteMultimediaReq  = pb.GetSiteMultimediaReq
	GetSiteMultimediaResp = pb.GetSiteMultimediaResp
	ListSitesReq          = pb.ListSitesReq
	ListSitesResp         = pb.ListSitesResp
	MultimediaInfo        = pb.MultimediaInfo
	SearchSitesReq        = pb.SearchSitesReq
	SearchSitesResp       = pb.SearchSitesResp
	SiteInfo              = pb.SiteInfo
	UpdateSiteReq         = pb.UpdateSiteReq

	SiteService interface {
		GetSiteByID(ctx context.Context, in *GetSiteByIDReq, opts ...grpc.CallOption) (*SiteInfo, error)
		ListSites(ctx context.Context, in *ListSitesReq, opts ...grpc.CallOption) (*ListSitesResp, error)
		SearchSites(ctx context.Context, in *SearchSitesReq, opts ...grpc.CallOption) (*SearchSitesResp, error)
		GetSiteMultimedia(ctx context.Context, in *GetSiteMultimediaReq, opts ...grpc.CallOption) (*GetSiteMultimediaResp, error)
		GetSiteDynamicInfo(ctx context.Context, in *GetSiteDynamicInfoReq, opts ...grpc.CallOption) (*DynamicInfo, error)
		// Admin methods
		CreateSite(ctx context.Context, in *CreateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error)
		UpdateSite(ctx context.Context, in *UpdateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error)
		DeleteSite(ctx context.Context, in *DeleteSiteReq, opts ...grpc.CallOption) (*DeleteSiteResp, error)
	}

	defaultSiteService struct {
		cli zrpc.Client
	}
)

func NewSiteService(cli zrpc.Client) SiteService {
	return &defaultSiteService{
		cli: cli,
	}
}

func (m *defaultSiteService) GetSiteByID(ctx context.Context, in *GetSiteByIDReq, opts ...grpc.CallOption) (*SiteInfo, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.GetSiteByID(ctx, in, opts...)
}

func (m *defaultSiteService) ListSites(ctx context.Context, in *ListSitesReq, opts ...grpc.CallOption) (*ListSitesResp, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.ListSites(ctx, in, opts...)
}

func (m *defaultSiteService) SearchSites(ctx context.Context, in *SearchSitesReq, opts ...grpc.CallOption) (*SearchSitesResp, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.SearchSites(ctx, in, opts...)
}

func (m *defaultSiteService) GetSiteMultimedia(ctx context.Context, in *GetSiteMultimediaReq, opts ...grpc.CallOption) (*GetSiteMultimediaResp, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.GetSiteMultimedia(ctx, in, opts...)
}

func (m *defaultSiteService) GetSiteDynamicInfo(ctx context.Context, in *GetSiteDynamicInfoReq, opts ...grpc.CallOption) (*DynamicInfo, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.GetSiteDynamicInfo(ctx, in, opts...)
}

// Admin methods
func (m *defaultSiteService) CreateSite(ctx context.Context, in *CreateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.CreateSite(ctx, in, opts...)
}

func (m *defaultSiteService) UpdateSite(ctx context.Context, in *UpdateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.UpdateSite(ctx, in, opts...)
}

func (m *defaultSiteService) DeleteSite(ctx context.Context, in *DeleteSiteReq, opts ...grpc.CallOption) (*DeleteSiteResp, error) {
	client := pb.NewSiteServiceClient(m.cli.Conn())
	return client.DeleteSite(ctx, in, opts...)
}
