// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	admin "site/internal/handler/admin/internal/handler/admin"
	"site/internal/handler/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// (Admin) Create a new site
				Method:  http.MethodPost,
				Path:    "/",
				Handler: admin.CreateSiteHandler(serverCtx),
			},
			{
				// (Admin) Update an existing site
				Method:  http.MethodPut,
				Path:    "/:siteID",
				Handler: admin.UpdateSiteHandler(serverCtx),
			},
			{
				// (Admin) Delete a site
				Method:  http.MethodDelete,
				Path:    "/:siteID",
				Handler: admin.DeleteSiteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin/sites"),
	)
}
