// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: site.proto

package server

import (
	"context"

	"site/internal/logic"
	"site/internal/svc"
	"site/pb"
)

type SiteServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSiteServiceServer
}

func NewSiteServiceServer(svcCtx *svc.ServiceContext) *SiteServiceServer {
	return &SiteServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SiteServiceServer) GetSiteByID(ctx context.Context, in *pb.GetSiteByIDReq) (*pb.SiteInfo, error) {
	l := logic.NewGetSiteByIDLogic(ctx, s.svcCtx)
	return l.GetSiteByID(in)
}

func (s *SiteServiceServer) ListSites(ctx context.Context, in *pb.ListSitesReq) (*pb.ListSitesResp, error) {
	l := logic.NewListSitesLogic(ctx, s.svcCtx)
	return l.ListSites(in)
}

func (s *SiteServiceServer) SearchSites(ctx context.Context, in *pb.SearchSitesReq) (*pb.SearchSitesResp, error) {
	l := logic.NewSearchSitesLogic(ctx, s.svcCtx)
	return l.SearchSites(in)
}

func (s *SiteServiceServer) GetSiteMultimedia(ctx context.Context, in *pb.GetSiteMultimediaReq) (*pb.GetSiteMultimediaResp, error) {
	l := logic.NewGetSiteMultimediaLogic(ctx, s.svcCtx)
	return l.GetSiteMultimedia(in)
}

func (s *SiteServiceServer) GetSiteDynamicInfo(ctx context.Context, in *pb.GetSiteDynamicInfoReq) (*pb.DynamicInfo, error) {
	l := logic.NewGetSiteDynamicInfoLogic(ctx, s.svcCtx)
	return l.GetSiteDynamicInfo(in)
}

// Admin methods
func (s *SiteServiceServer) CreateSite(ctx context.Context, in *pb.CreateSiteReq) (*pb.SiteInfo, error) {
	l := logic.NewCreateSiteLogic(ctx, s.svcCtx)
	return l.CreateSite(in)
}

func (s *SiteServiceServer) UpdateSite(ctx context.Context, in *pb.UpdateSiteReq) (*pb.SiteInfo, error) {
	l := logic.NewUpdateSiteLogic(ctx, s.svcCtx)
	return l.UpdateSite(in)
}

func (s *SiteServiceServer) DeleteSite(ctx context.Context, in *pb.DeleteSiteReq) (*pb.DeleteSiteResp, error) {
	l := logic.NewDeleteSiteLogic(ctx, s.svcCtx)
	return l.DeleteSite(in)
}
