// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: site.proto

package server

import (
	"context"

	"site/internal/logic"
	"site/internal/svc"
	"site/site"
)

type SiteServer struct {
	svcCtx *svc.ServiceContext
	site.UnimplementedSiteServer
}

func NewSiteServer(svcCtx *svc.ServiceContext) *SiteServer {
	return &SiteServer{
		svcCtx: svcCtx,
	}
}

func (s *SiteServer) Ping(ctx context.Context, in *site.Request) (*site.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
