// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DynamicInfo struct {
	SiteID       string   `json:"siteId"`
	OpeningHours string   `json:"openingHours,optional"` // Could be structured JSON string or text
	TicketPrice  string   `json:"ticketPrice,optional"`
	Notices      []string `json:"notices,optional"`
	UpdatedAt    int64    `json:"updatedAt,optional"` // When this dynamic info was last updated
}

type GetSiteDynamicInfoReq struct {
	SiteID string `path:"siteID"`
}

type GetSiteMultimediaReq struct {
	SiteID string `path:"siteID"`
}

type GetSiteMultimediaResp struct {
	Multimedia []Multimedia `json:"multimedia"`
}

type ListSitesReq struct {
	Category         string `form:"category,optional"`
	Region           string `form:"region,optional"`
	HistoricalPeriod string `form:"historicalPeriod,optional"`
	Page             int    `form:"page,optional,default=1"`
	PageSize         int    `form:"pageSize,optional,default=10"`
}

type ListSitesResp struct {
	Sites    []Site `json:"sites"`
	Total    int64  `json:"total"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
}

type Multimedia struct {
	Id          string `json:"id"`
	SiteID      string `json:"siteId"`
	Type        string `json:"type"` // image, video, audio
	Url         string `json:"url"`
	Description string `json:"description,optional"`
	CreatedAt   int64  `json:"createdAt,optional"`
	UpdatedAt   int64  `json:"updatedAt,optional"`
}

type SearchSitesReq struct {
	Keyword  string `form:"keyword"`
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=10"`
}

type SearchSitesResp struct {
	Sites    []Site `json:"sites"`
	Total    int64  `json:"total"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
}
