// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DynamicInfo struct {
	SiteID       string   `json:"siteId"`
	OpeningHours string   `json:"openingHours,optional"` // Could be structured JSON string or text
	TicketPrice  string   `json:"ticketPrice,optional"`
	Notices      []string `json:"notices,optional"`
	UpdatedAt    int64    `json:"updatedAt,optional"` // When this dynamic info was last updated
}

type GetSiteByIDReq struct {
	SiteID string `path:"siteID"`
}

type GetSiteDynamicInfoReq struct {
	SiteID string `path:"siteID"`
}

type GetSiteMultimediaReq struct {
	SiteID string `path:"siteID"`
}

type GetSiteMultimediaResp struct {
	Multimedia []Multimedia `json:"multimedia"`
}

type ListSitesReq struct {
	Category         string `form:"category,optional"`
	Region           string `form:"region,optional"`
	HistoricalPeriod string `form:"historicalPeriod,optional"`
	Page             int    `form:"page,optional,default=1"`
	PageSize         int    `form:"pageSize,optional,default=10"`
}

type ListSitesResp struct {
	Sites    []Site `json:"sites"`
	Total    int64  `json:"total"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
}

type SearchSitesReq struct {
	Keyword  string `form:"keyword"`
	Page     int    `form:"page,optional,default=1"`
	PageSize int    `form:"pageSize,optional,default=10"`
}

type SearchSitesResp struct {
	Sites    []Site `json:"sites"`
	Total    int64  `json:"total"`
	Page     int    `json:"page"`
	PageSize int    `json:"pageSize"`
}

type Site struct {
	Id               string  `json:"id"`
	Name             string  `json:"name"`
	Description      string  `json:"description,optional"`
	Category         string  `json:"category,optional"`         // e.g., Museum, Monument, Landmark
	Region           string  `json:"region,optional"`           // Geographical area
	HistoricalPeriod string  `json:"historicalPeriod,optional"` // e.g., Ming Dynasty, Roman Empire
	Latitude         float64 `json:"latitude,optional"`
	Longitude        float64 `json:"longitude,optional"`
	Address          string  `json:"address,optional"`
	CreatedAt        int64   `json:"createdAt,optional"`
	UpdatedAt        int64   `json:"updatedAt,optional"`
}
