// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateSiteReq struct {
	Name             string  `json:"name"`
	Description      string  `json:"description,optional"`
	Category         string  `json:"category,optional"`
	Region           string  `json:"region,optional"`
	HistoricalPeriod string  `json:"historicalPeriod,optional"`
	Latitude         float64 `json:"latitude,optional"`
	Longitude        float64 `json:"longitude,optional"`
	Address          string  `json:"address,optional"`
}

type DeleteSiteResp struct {
	Message string `json:"message"`
}

type Multimedia struct {
	Id          string `json:"id"`
	SiteID      string `json:"siteId"`
	Type        string `json:"type"` // image, video, audio
	Url         string `json:"url"`
	Description string `json:"description,optional"`
	CreatedAt   int64  `json:"createdAt,optional"`
	UpdatedAt   int64  `json:"updatedAt,optional"`
}

type UpdateSiteReq struct {
	SiteID           string  `path:"siteID"`
	Name             string  `json:"name,optional"`
	Description      string  `json:"description,optional"`
	Category         string  `json:"category,optional"`
	Region           string  `json:"region,optional"`
	HistoricalPeriod string  `json:"historicalPeriod,optional"`
	Latitude         float64 `json:"latitude,optional"`
	Longitude        float64 `json:"longitude,optional"`
	Address          string  `json:"address,optional"`
}
