// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: site.proto

package siteclient

import (
	"context"

	"site/site"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = site.Request
	Response = site.Response

	Site interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSite struct {
		cli zrpc.Client
	}
)

func NewSite(cli zrpc.Client) Site {
	return &defaultSite{
		cli: cli,
	}
}

func (m *defaultSite) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := site.NewSiteClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
