// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pb/site.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SiteService_GetSiteByID_FullMethodName        = "/pb.SiteService/GetSiteByID"
	SiteService_ListSites_FullMethodName          = "/pb.SiteService/ListSites"
	SiteService_SearchSites_FullMethodName        = "/pb.SiteService/SearchSites"
	SiteService_GetSiteMultimedia_FullMethodName  = "/pb.SiteService/GetSiteMultimedia"
	SiteService_GetSiteDynamicInfo_FullMethodName = "/pb.SiteService/GetSiteDynamicInfo"
	SiteService_CreateSite_FullMethodName         = "/pb.SiteService/CreateSite"
	SiteService_UpdateSite_FullMethodName         = "/pb.SiteService/UpdateSite"
	SiteService_DeleteSite_FullMethodName         = "/pb.SiteService/DeleteSite"
)

// SiteServiceClient is the client API for SiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SiteServiceClient interface {
	GetSiteByID(ctx context.Context, in *GetSiteByIDReq, opts ...grpc.CallOption) (*SiteInfo, error)
	ListSites(ctx context.Context, in *ListSitesReq, opts ...grpc.CallOption) (*ListSitesResp, error)
	SearchSites(ctx context.Context, in *SearchSitesReq, opts ...grpc.CallOption) (*SearchSitesResp, error)
	GetSiteMultimedia(ctx context.Context, in *GetSiteMultimediaReq, opts ...grpc.CallOption) (*GetSiteMultimediaResp, error)
	GetSiteDynamicInfo(ctx context.Context, in *GetSiteDynamicInfoReq, opts ...grpc.CallOption) (*DynamicInfo, error)
	// Admin methods
	CreateSite(ctx context.Context, in *CreateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error)
	UpdateSite(ctx context.Context, in *UpdateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error)
	DeleteSite(ctx context.Context, in *DeleteSiteReq, opts ...grpc.CallOption) (*DeleteSiteResp, error)
}

type siteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteServiceClient(cc grpc.ClientConnInterface) SiteServiceClient {
	return &siteServiceClient{cc}
}

func (c *siteServiceClient) GetSiteByID(ctx context.Context, in *GetSiteByIDReq, opts ...grpc.CallOption) (*SiteInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiteInfo)
	err := c.cc.Invoke(ctx, SiteService_GetSiteByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) ListSites(ctx context.Context, in *ListSitesReq, opts ...grpc.CallOption) (*ListSitesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSitesResp)
	err := c.cc.Invoke(ctx, SiteService_ListSites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) SearchSites(ctx context.Context, in *SearchSitesReq, opts ...grpc.CallOption) (*SearchSitesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSitesResp)
	err := c.cc.Invoke(ctx, SiteService_SearchSites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetSiteMultimedia(ctx context.Context, in *GetSiteMultimediaReq, opts ...grpc.CallOption) (*GetSiteMultimediaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSiteMultimediaResp)
	err := c.cc.Invoke(ctx, SiteService_GetSiteMultimedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) GetSiteDynamicInfo(ctx context.Context, in *GetSiteDynamicInfoReq, opts ...grpc.CallOption) (*DynamicInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DynamicInfo)
	err := c.cc.Invoke(ctx, SiteService_GetSiteDynamicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) CreateSite(ctx context.Context, in *CreateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiteInfo)
	err := c.cc.Invoke(ctx, SiteService_CreateSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) UpdateSite(ctx context.Context, in *UpdateSiteReq, opts ...grpc.CallOption) (*SiteInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiteInfo)
	err := c.cc.Invoke(ctx, SiteService_UpdateSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteServiceClient) DeleteSite(ctx context.Context, in *DeleteSiteReq, opts ...grpc.CallOption) (*DeleteSiteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSiteResp)
	err := c.cc.Invoke(ctx, SiteService_DeleteSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServiceServer is the server API for SiteService service.
// All implementations must embed UnimplementedSiteServiceServer
// for forward compatibility.
type SiteServiceServer interface {
	GetSiteByID(context.Context, *GetSiteByIDReq) (*SiteInfo, error)
	ListSites(context.Context, *ListSitesReq) (*ListSitesResp, error)
	SearchSites(context.Context, *SearchSitesReq) (*SearchSitesResp, error)
	GetSiteMultimedia(context.Context, *GetSiteMultimediaReq) (*GetSiteMultimediaResp, error)
	GetSiteDynamicInfo(context.Context, *GetSiteDynamicInfoReq) (*DynamicInfo, error)
	// Admin methods
	CreateSite(context.Context, *CreateSiteReq) (*SiteInfo, error)
	UpdateSite(context.Context, *UpdateSiteReq) (*SiteInfo, error)
	DeleteSite(context.Context, *DeleteSiteReq) (*DeleteSiteResp, error)
	mustEmbedUnimplementedSiteServiceServer()
}

// UnimplementedSiteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSiteServiceServer struct{}

func (UnimplementedSiteServiceServer) GetSiteByID(context.Context, *GetSiteByIDReq) (*SiteInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteByID not implemented")
}
func (UnimplementedSiteServiceServer) ListSites(context.Context, *ListSitesReq) (*ListSitesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSites not implemented")
}
func (UnimplementedSiteServiceServer) SearchSites(context.Context, *SearchSitesReq) (*SearchSitesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSites not implemented")
}
func (UnimplementedSiteServiceServer) GetSiteMultimedia(context.Context, *GetSiteMultimediaReq) (*GetSiteMultimediaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteMultimedia not implemented")
}
func (UnimplementedSiteServiceServer) GetSiteDynamicInfo(context.Context, *GetSiteDynamicInfoReq) (*DynamicInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteDynamicInfo not implemented")
}
func (UnimplementedSiteServiceServer) CreateSite(context.Context, *CreateSiteReq) (*SiteInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSite not implemented")
}
func (UnimplementedSiteServiceServer) UpdateSite(context.Context, *UpdateSiteReq) (*SiteInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSite not implemented")
}
func (UnimplementedSiteServiceServer) DeleteSite(context.Context, *DeleteSiteReq) (*DeleteSiteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSite not implemented")
}
func (UnimplementedSiteServiceServer) mustEmbedUnimplementedSiteServiceServer() {}
func (UnimplementedSiteServiceServer) testEmbeddedByValue()                     {}

// UnsafeSiteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SiteServiceServer will
// result in compilation errors.
type UnsafeSiteServiceServer interface {
	mustEmbedUnimplementedSiteServiceServer()
}

func RegisterSiteServiceServer(s grpc.ServiceRegistrar, srv SiteServiceServer) {
	// If the following call pancis, it indicates UnimplementedSiteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SiteService_ServiceDesc, srv)
}

func _SiteService_GetSiteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetSiteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetSiteByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetSiteByID(ctx, req.(*GetSiteByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_ListSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSitesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).ListSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_ListSites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).ListSites(ctx, req.(*ListSitesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_SearchSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSitesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).SearchSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_SearchSites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).SearchSites(ctx, req.(*SearchSitesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetSiteMultimedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteMultimediaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetSiteMultimedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetSiteMultimedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetSiteMultimedia(ctx, req.(*GetSiteMultimediaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_GetSiteDynamicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteDynamicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).GetSiteDynamicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_GetSiteDynamicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).GetSiteDynamicInfo(ctx, req.(*GetSiteDynamicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_CreateSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSiteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).CreateSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_CreateSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).CreateSite(ctx, req.(*CreateSiteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_UpdateSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSiteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).UpdateSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_UpdateSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).UpdateSite(ctx, req.(*UpdateSiteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteService_DeleteSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSiteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).DeleteSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteService_DeleteSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).DeleteSite(ctx, req.(*DeleteSiteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SiteService_ServiceDesc is the grpc.ServiceDesc for SiteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SiteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SiteService",
	HandlerType: (*SiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSiteByID",
			Handler:    _SiteService_GetSiteByID_Handler,
		},
		{
			MethodName: "ListSites",
			Handler:    _SiteService_ListSites_Handler,
		},
		{
			MethodName: "SearchSites",
			Handler:    _SiteService_SearchSites_Handler,
		},
		{
			MethodName: "GetSiteMultimedia",
			Handler:    _SiteService_GetSiteMultimedia_Handler,
		},
		{
			MethodName: "GetSiteDynamicInfo",
			Handler:    _SiteService_GetSiteDynamicInfo_Handler,
		},
		{
			MethodName: "CreateSite",
			Handler:    _SiteService_CreateSite_Handler,
		},
		{
			MethodName: "UpdateSite",
			Handler:    _SiteService_UpdateSite_Handler,
		},
		{
			MethodName: "DeleteSite",
			Handler:    _SiteService_DeleteSite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/site.proto",
}
