// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/site.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category         string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Region           string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	HistoricalPeriod string                 `protobuf:"bytes,6,opt,name=historical_period,json=historicalPeriod,proto3" json:"historical_period,omitempty"`
	Latitude         float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address          string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SiteInfo) Reset() {
	*x = SiteInfo{}
	mi := &file_pb_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteInfo) ProtoMessage() {}

func (x *SiteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteInfo.ProtoReflect.Descriptor instead.
func (*SiteInfo) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{0}
}

func (x *SiteInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SiteInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SiteInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SiteInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SiteInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SiteInfo) GetHistoricalPeriod() string {
	if x != nil {
		return x.HistoricalPeriod
	}
	return ""
}

func (x *SiteInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SiteInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SiteInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SiteInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SiteInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type MultimediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteId        string                 `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g., "image", "video", "audio"
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultimediaInfo) Reset() {
	*x = MultimediaInfo{}
	mi := &file_pb_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultimediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultimediaInfo) ProtoMessage() {}

func (x *MultimediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultimediaInfo.ProtoReflect.Descriptor instead.
func (*MultimediaInfo) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{1}
}

func (x *MultimediaInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MultimediaInfo) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *MultimediaInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MultimediaInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MultimediaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MultimediaInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MultimediaInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DynamicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	OpeningHours  string                 `protobuf:"bytes,2,opt,name=opening_hours,json=openingHours,proto3" json:"opening_hours,omitempty"`
	TicketPrice   string                 `protobuf:"bytes,3,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	Notices       []string               `protobuf:"bytes,4,rep,name=notices,proto3" json:"notices,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicInfo) Reset() {
	*x = DynamicInfo{}
	mi := &file_pb_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicInfo) ProtoMessage() {}

func (x *DynamicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicInfo.ProtoReflect.Descriptor instead.
func (*DynamicInfo) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{2}
}

func (x *DynamicInfo) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *DynamicInfo) GetOpeningHours() string {
	if x != nil {
		return x.OpeningHours
	}
	return ""
}

func (x *DynamicInfo) GetTicketPrice() string {
	if x != nil {
		return x.TicketPrice
	}
	return ""
}

func (x *DynamicInfo) GetNotices() []string {
	if x != nil {
		return x.Notices
	}
	return nil
}

func (x *DynamicInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// GetSiteByID
type GetSiteByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteByIDReq) Reset() {
	*x = GetSiteByIDReq{}
	mi := &file_pb_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteByIDReq) ProtoMessage() {}

func (x *GetSiteByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteByIDReq.ProtoReflect.Descriptor instead.
func (*GetSiteByIDReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{3}
}

func (x *GetSiteByIDReq) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

// ListSites
type ListSitesReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Category         string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Region           string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	HistoricalPeriod string                 `protobuf:"bytes,3,opt,name=historical_period,json=historicalPeriod,proto3" json:"historical_period,omitempty"`
	Page             int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListSitesReq) Reset() {
	*x = ListSitesReq{}
	mi := &file_pb_site_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesReq) ProtoMessage() {}

func (x *ListSitesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesReq.ProtoReflect.Descriptor instead.
func (*ListSitesReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{4}
}

func (x *ListSitesReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListSitesReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListSitesReq) GetHistoricalPeriod() string {
	if x != nil {
		return x.HistoricalPeriod
	}
	return ""
}

func (x *ListSitesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSitesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSitesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sites         []*SiteInfo            `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesResp) Reset() {
	*x = ListSitesResp{}
	mi := &file_pb_site_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesResp) ProtoMessage() {}

func (x *ListSitesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesResp.ProtoReflect.Descriptor instead.
func (*ListSitesResp) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{5}
}

func (x *ListSitesResp) GetSites() []*SiteInfo {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *ListSitesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSitesResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSitesResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// SearchSites
type SearchSitesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSitesReq) Reset() {
	*x = SearchSitesReq{}
	mi := &file_pb_site_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSitesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSitesReq) ProtoMessage() {}

func (x *SearchSitesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSitesReq.ProtoReflect.Descriptor instead.
func (*SearchSitesReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{6}
}

func (x *SearchSitesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSitesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchSitesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchSitesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sites         []*SiteInfo            `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSitesResp) Reset() {
	*x = SearchSitesResp{}
	mi := &file_pb_site_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSitesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSitesResp) ProtoMessage() {}

func (x *SearchSitesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSitesResp.ProtoReflect.Descriptor instead.
func (*SearchSitesResp) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{7}
}

func (x *SearchSitesResp) GetSites() []*SiteInfo {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *SearchSitesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchSitesResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchSitesResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetSiteMultimedia
type GetSiteMultimediaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteMultimediaReq) Reset() {
	*x = GetSiteMultimediaReq{}
	mi := &file_pb_site_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteMultimediaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteMultimediaReq) ProtoMessage() {}

func (x *GetSiteMultimediaReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteMultimediaReq.ProtoReflect.Descriptor instead.
func (*GetSiteMultimediaReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{8}
}

func (x *GetSiteMultimediaReq) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

type GetSiteMultimediaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multimedia    []*MultimediaInfo      `protobuf:"bytes,1,rep,name=multimedia,proto3" json:"multimedia,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteMultimediaResp) Reset() {
	*x = GetSiteMultimediaResp{}
	mi := &file_pb_site_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteMultimediaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteMultimediaResp) ProtoMessage() {}

func (x *GetSiteMultimediaResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteMultimediaResp.ProtoReflect.Descriptor instead.
func (*GetSiteMultimediaResp) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{9}
}

func (x *GetSiteMultimediaResp) GetMultimedia() []*MultimediaInfo {
	if x != nil {
		return x.Multimedia
	}
	return nil
}

// GetSiteDynamicInfo
type GetSiteDynamicInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteDynamicInfoReq) Reset() {
	*x = GetSiteDynamicInfoReq{}
	mi := &file_pb_site_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteDynamicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteDynamicInfoReq) ProtoMessage() {}

func (x *GetSiteDynamicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteDynamicInfoReq.ProtoReflect.Descriptor instead.
func (*GetSiteDynamicInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{10}
}

func (x *GetSiteDynamicInfoReq) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

// CreateSite
type CreateSiteReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category         string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Region           string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	HistoricalPeriod string                 `protobuf:"bytes,5,opt,name=historical_period,json=historicalPeriod,proto3" json:"historical_period,omitempty"`
	Latitude         float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address          string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSiteReq) Reset() {
	*x = CreateSiteReq{}
	mi := &file_pb_site_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteReq) ProtoMessage() {}

func (x *CreateSiteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteReq.ProtoReflect.Descriptor instead.
func (*CreateSiteReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSiteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSiteReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateSiteReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateSiteReq) GetHistoricalPeriod() string {
	if x != nil {
		return x.HistoricalPeriod
	}
	return ""
}

func (x *CreateSiteReq) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateSiteReq) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateSiteReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// UpdateSite
type UpdateSiteReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SiteId           string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category         string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Region           string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	HistoricalPeriod string                 `protobuf:"bytes,6,opt,name=historical_period,json=historicalPeriod,proto3" json:"historical_period,omitempty"`
	Latitude         float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address          string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateSiteReq) Reset() {
	*x = UpdateSiteReq{}
	mi := &file_pb_site_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteReq) ProtoMessage() {}

func (x *UpdateSiteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteReq.ProtoReflect.Descriptor instead.
func (*UpdateSiteReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSiteReq) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *UpdateSiteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSiteReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSiteReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateSiteReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpdateSiteReq) GetHistoricalPeriod() string {
	if x != nil {
		return x.HistoricalPeriod
	}
	return ""
}

func (x *UpdateSiteReq) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateSiteReq) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateSiteReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// DeleteSite
type DeleteSiteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSiteReq) Reset() {
	*x = DeleteSiteReq{}
	mi := &file_pb_site_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSiteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSiteReq) ProtoMessage() {}

func (x *DeleteSiteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSiteReq.ProtoReflect.Descriptor instead.
func (*DeleteSiteReq) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSiteReq) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

type DeleteSiteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSiteResp) Reset() {
	*x = DeleteSiteResp{}
	mi := &file_pb_site_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSiteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSiteResp) ProtoMessage() {}

func (x *DeleteSiteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_site_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSiteResp.ProtoReflect.Descriptor instead.
func (*DeleteSiteResp) Descriptor() ([]byte, []int) {
	return file_pb_site_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSiteResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_site_proto protoreflect.FileDescriptor

const file_pb_site_proto_rawDesc = "" +
	"\n" +
	"\rpb/site.proto\x12\x02pb\"\xc3\x02\n" +
	"\bSiteInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12+\n" +
	"\x11historical_period\x18\x06 \x01(\tR\x10historicalPeriod\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xbf\x01\n" +
	"\x0eMultimediaInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\tR\x06siteId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xa7\x01\n" +
	"\vDynamicInfo\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12#\n" +
	"\ropening_hours\x18\x02 \x01(\tR\fopeningHours\x12!\n" +
	"\fticket_price\x18\x03 \x01(\tR\vticketPrice\x12\x18\n" +
	"\anotices\x18\x04 \x03(\tR\anotices\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\")\n" +
	"\x0eGetSiteByIDReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\"\xa0\x01\n" +
	"\fListSitesReq\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12+\n" +
	"\x11historical_period\x18\x03 \x01(\tR\x10historicalPeriod\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"z\n" +
	"\rListSitesResp\x12\"\n" +
	"\x05sites\x18\x01 \x03(\v2\f.pb.SiteInfoR\x05sites\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"[\n" +
	"\x0eSearchSitesReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"|\n" +
	"\x0fSearchSitesResp\x12\"\n" +
	"\x05sites\x18\x01 \x03(\v2\f.pb.SiteInfoR\x05sites\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"/\n" +
	"\x14GetSiteMultimediaReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\"K\n" +
	"\x15GetSiteMultimediaResp\x122\n" +
	"\n" +
	"multimedia\x18\x01 \x03(\v2\x12.pb.MultimediaInfoR\n" +
	"multimedia\"0\n" +
	"\x15GetSiteDynamicInfoReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\"\xfa\x01\n" +
	"\rCreateSiteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12+\n" +
	"\x11historical_period\x18\x05 \x01(\tR\x10historicalPeriod\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"\x93\x02\n" +
	"\rUpdateSiteReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12+\n" +
	"\x11historical_period\x18\x06 \x01(\tR\x10historicalPeriod\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\"(\n" +
	"\rDeleteSiteReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\"*\n" +
	"\x0eDeleteSiteResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc7\x03\n" +
	"\vSiteService\x12/\n" +
	"\vGetSiteByID\x12\x12.pb.GetSiteByIDReq\x1a\f.pb.SiteInfo\x120\n" +
	"\tListSites\x12\x10.pb.ListSitesReq\x1a\x11.pb.ListSitesResp\x126\n" +
	"\vSearchSites\x12\x12.pb.SearchSitesReq\x1a\x13.pb.SearchSitesResp\x12H\n" +
	"\x11GetSiteMultimedia\x12\x18.pb.GetSiteMultimediaReq\x1a\x19.pb.GetSiteMultimediaResp\x12@\n" +
	"\x12GetSiteDynamicInfo\x12\x19.pb.GetSiteDynamicInfoReq\x1a\x0f.pb.DynamicInfo\x12-\n" +
	"\n" +
	"CreateSite\x12\x11.pb.CreateSiteReq\x1a\f.pb.SiteInfo\x12-\n" +
	"\n" +
	"UpdateSite\x12\x11.pb.UpdateSiteReq\x1a\f.pb.SiteInfo\x123\n" +
	"\n" +
	"DeleteSite\x12\x11.pb.DeleteSiteReq\x1a\x12.pb.DeleteSiteRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_site_proto_rawDescOnce sync.Once
	file_pb_site_proto_rawDescData []byte
)

func file_pb_site_proto_rawDescGZIP() []byte {
	file_pb_site_proto_rawDescOnce.Do(func() {
		file_pb_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_site_proto_rawDesc), len(file_pb_site_proto_rawDesc)))
	})
	return file_pb_site_proto_rawDescData
}

var file_pb_site_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_site_proto_goTypes = []any{
	(*SiteInfo)(nil),              // 0: pb.SiteInfo
	(*MultimediaInfo)(nil),        // 1: pb.MultimediaInfo
	(*DynamicInfo)(nil),           // 2: pb.DynamicInfo
	(*GetSiteByIDReq)(nil),        // 3: pb.GetSiteByIDReq
	(*ListSitesReq)(nil),          // 4: pb.ListSitesReq
	(*ListSitesResp)(nil),         // 5: pb.ListSitesResp
	(*SearchSitesReq)(nil),        // 6: pb.SearchSitesReq
	(*SearchSitesResp)(nil),       // 7: pb.SearchSitesResp
	(*GetSiteMultimediaReq)(nil),  // 8: pb.GetSiteMultimediaReq
	(*GetSiteMultimediaResp)(nil), // 9: pb.GetSiteMultimediaResp
	(*GetSiteDynamicInfoReq)(nil), // 10: pb.GetSiteDynamicInfoReq
	(*CreateSiteReq)(nil),         // 11: pb.CreateSiteReq
	(*UpdateSiteReq)(nil),         // 12: pb.UpdateSiteReq
	(*DeleteSiteReq)(nil),         // 13: pb.DeleteSiteReq
	(*DeleteSiteResp)(nil),        // 14: pb.DeleteSiteResp
}
var file_pb_site_proto_depIdxs = []int32{
	0,  // 0: pb.ListSitesResp.sites:type_name -> pb.SiteInfo
	0,  // 1: pb.SearchSitesResp.sites:type_name -> pb.SiteInfo
	1,  // 2: pb.GetSiteMultimediaResp.multimedia:type_name -> pb.MultimediaInfo
	3,  // 3: pb.SiteService.GetSiteByID:input_type -> pb.GetSiteByIDReq
	4,  // 4: pb.SiteService.ListSites:input_type -> pb.ListSitesReq
	6,  // 5: pb.SiteService.SearchSites:input_type -> pb.SearchSitesReq
	8,  // 6: pb.SiteService.GetSiteMultimedia:input_type -> pb.GetSiteMultimediaReq
	10, // 7: pb.SiteService.GetSiteDynamicInfo:input_type -> pb.GetSiteDynamicInfoReq
	11, // 8: pb.SiteService.CreateSite:input_type -> pb.CreateSiteReq
	12, // 9: pb.SiteService.UpdateSite:input_type -> pb.UpdateSiteReq
	13, // 10: pb.SiteService.DeleteSite:input_type -> pb.DeleteSiteReq
	0,  // 11: pb.SiteService.GetSiteByID:output_type -> pb.SiteInfo
	5,  // 12: pb.SiteService.ListSites:output_type -> pb.ListSitesResp
	7,  // 13: pb.SiteService.SearchSites:output_type -> pb.SearchSitesResp
	9,  // 14: pb.SiteService.GetSiteMultimedia:output_type -> pb.GetSiteMultimediaResp
	2,  // 15: pb.SiteService.GetSiteDynamicInfo:output_type -> pb.DynamicInfo
	0,  // 16: pb.SiteService.CreateSite:output_type -> pb.SiteInfo
	0,  // 17: pb.SiteService.UpdateSite:output_type -> pb.SiteInfo
	14, // 18: pb.SiteService.DeleteSite:output_type -> pb.DeleteSiteResp
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_site_proto_init() }
func file_pb_site_proto_init() {
	if File_pb_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_site_proto_rawDesc), len(file_pb_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_site_proto_goTypes,
		DependencyIndexes: file_pb_site_proto_depIdxs,
		MessageInfos:      file_pb_site_proto_msgTypes,
	}.Build()
	File_pb_site_proto = out.File
	file_pb_site_proto_goTypes = nil
	file_pb_site_proto_depIdxs = nil
}
