// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	site "site/internal/handler/public/internal/handler/site"
	"site/internal/handler/public/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// List sites with filters and pagination
				Method:  http.MethodGet,
				Path:    "/",
				Handler: site.ListSitesHandler(serverCtx),
			},
			{
				// Get site details by ID
				Method:  http.MethodGet,
				Path:    "/:siteID",
				Handler: site.GetSiteByIDHandler(serverCtx),
			},
			{
				// Get dynamic information for a site (opening hours, ticket prices)
				Method:  http.MethodGet,
				Path:    "/:siteID/dynamic",
				Handler: site.GetSiteDynamicInfoHandler(serverCtx),
			},
			{
				// Get multimedia resources for a site
				Method:  http.MethodGet,
				Path:    "/:siteID/multimedia",
				Handler: site.GetSiteMultimediaHandler(serverCtx),
			},
			{
				// Search sites by keyword
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: site.SearchSitesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/sites"),
	)
}
